name: Generate GitHub-Profile-Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate snake
        uses: platane/snk@v3
        with:
          github_user_name: FlyingVoodoo
          outputs: dist/github-snake.svg
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/github-snake.svg
          git commit -m "Generate GitHub snake"
          git push
