name: Generate GitHub-Profile-Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: FlyingVoodoo
          outputs: dist/github-snake.svg
